### PR TITLE
use docker:dind as run container

### PR DESCRIPTION
**Pull request by booniepepper**
*Issue #, if available:*

*Description of changes:*

Use `docker:dind`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by teruokun** [comment]
I had assumed the reason it was a todo was due to potential incompatibilities or otherwise, so I’ll let @lesiw weigh in, but I mean, the checks pass (though I imagine we need some better basic use testing rather than build alone) and it looks straight forwards to me.  So I’ll approve under the caveat I don’t know if there more necessary for compatibility between the 2

**Review by teruokun — APPROVED** [review]
Defer to @lesiw on what else need to be changed for this to work, but LGTM

**Comment by booniepepper** [comment]
I'm going to make this a draft for now. Some discussion on [the /dev/tty discord](https://discord.gg/QHZAqZgsZN)

**Review by lesiw — APPROVED** [review]

**Comment by lesiw** [comment]
This change is good, but buildwarden is broken for other reasons - I'll merge this in and create a new PR to fix DNS.

**Pull request merged**
